# Reference: https://docs.docker.com/reference/compose-file/
name: esp32-fall-detector

services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    hostname: postgres
    image: postgres:16.10-alpine
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: uvicorn server.app:app --host 0.0.0.0 --port 12110
    container_name: server
    depends_on:
      - postgres
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    hostname: server
    working_dir: /app
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: web
    depends_on:
      - server
    hostname: web
    ports:
      - "80:80"
    restart: unless-stopped
